### ISSUE TITLE
How to train model in batch size = 1

### ISSUE THREAD

**Issue by Hydrogenion** [DylanWusee/pointconv_pytorch#6]
How to train model in batch size = 1
I got this error:

Traceback (most recent call last):
  File "/Users/name/PycharmProjects/pointconv_pytorch-master/model/pointconv.py", line 45, in <module>
    output= model(input)
  File "/Users/name/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/name/PycharmProjects/pointconv_pytorch-master/model/pointconv.py", line 30, in forward
    l3_xyz, l3_points = self.sa3(l2_xyz, l2_points)
  File "/Users/name/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/name/PycharmProjects/pointconv_pytorch-master/utils/pointconv_util.py", line 374, in forward
    new_points = self.bn_linear(new_points.permute(0, 2, 1))
  File "/Users/name/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/name/anaconda3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/Users/name/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1619, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 1024, 1])

**Comment by DylanWusee** [comment]
This is a bug in Pytorch when uisng BatchNorm1d. 
Please train the model with batchsize>=2.
